---

- name: Install net core runtime
  gather_facts: false
  hosts: "{{ host | default('all') }}"
  tasks:

    - name: Update repositories cache
      apt:
        update_cache: yes    
             
    - name: Add packages
      shell: /usr/bin/wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
    
    - name: Add repo location
      shell: /usr/bin/dpkg -i packages-microsoft-prod.deb
    
    - name: Add repo location
      shell: add-apt-repository universe
    
    - name: Add repo location
      apt_repository:
       repo: universe
       state: present
    
    - name: Install packages
      apt:
        name: apt-transport-https
        state: present
    
    - name: Update repositories cache
      apt:
       update_cache: yes    
  
    - name: Install packages
      apt:
        name: aspnetcore-runtime-2.2
        state: present